name: Quality assurance

on:
  push:
    branches:
      - master
  schedule:
    - cron:  "0 3 * * 1-5"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./...
    