name: Quality assurance

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: f6e3d8596abc6064ac1bcf10200ed8c45bd0c489dfd180a014d4f958869bf4eb
        with:
          coverageCommand: go test -coverprofile c.out ./...
          debug: true
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
